"""Create watchlist_stocks table

Revision ID: 772147ac8336
Revises: 49550d37336e
Create Date: 2025-04-18 20:34:28.290698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772147ac8336'
down_revision = '49550d37336e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_stocks',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'stock_id')
    )
    op.drop_table('watchlist_stock')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('watchlist_stock',
    sa.Column('watchlist_id', sa.INTEGER(), nullable=False),
    sa.Column('stock_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'stock_id')
    )
    op.drop_table('watchlist_stocks')
    # ### end Alembic commands ###
